version: '2'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db
    networks:
      - mongo-compose-network

  catalog:
    build: catalog/.
    container_name: catalog
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - discount
    links:
      - mongo
      - discount
    networks:
      - mongo-compose-network

  discount:
    build: discount/.
    command: npm run start
    volumes:
      - .discount/dist:/server/dist
    ports:
      - 50051:50051
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge